name: Publish Docker image

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  workflow_dispatch:
  push:
    branches: ["feature"]

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: registry.cn-hangzhou.aliyuncs.com

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check disk space
        run: df . -h

      - name: Free disk space
        run: |
          sudo docker rmi $(docker image ls -aq) >/dev/null 2>&1 || true
          sudo rm -rf \
            /usr/share/dotnet /usr/local/lib/android /opt/ghc \
            /usr/local/share/powershell /usr/share/swift /usr/local/.ghcup \
            /usr/lib/jvm || true

      - name: Extract version
        run: |
          pip install poetry
          VERSION_TAG=$(poetry version --short)
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV

      # Uses the `docker/login-action` action to log in to the Container registry registry using the account and password that will publish the packages. Once published, the packages are scoped to the account defined here.
      - name: Login to ACR Hangzhou region
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USER }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push base image
        env:
          IMAGE_TAG: ${{env.VERSION_TAG}}
        run: |
          docker build -t ${{ env.REGISTRY }}/mybigpai/pairag:$IMAGE_TAG .
          docker push ${{ env.REGISTRY }}/mybigpai/pairag:$IMAGE_TAG

      - name: Build and push UI image
        env:
          IMAGE_TAG: ${{env.VERSION_TAG}}-ui
        run: |
          docker build -t ${{ env.REGISTRY }}/mybigpai/pairag:$IMAGE_TAG -f Dockerfile_ui .
          docker push ${{ env.REGISTRY }}/mybigpai/pairag:$IMAGE_TAG

      - name: Build and push nginx image
        env:
          IMAGE_TAG: ${{env.VERSION_TAG}}-nginx
        run: |
          docker build -t ${{ env.REGISTRY }}/mybigpai/pairag:$IMAGE_TAG -f Dockerfile_nginx .
          docker push ${{ env.REGISTRY }}/mybigpai/pairag:$IMAGE_TAG

      - name: Build and push GPU image
        env:
          IMAGE_TAG: ${{env.VERSION_TAG}}-gpu
        run: |
          docker build -t ${{ env.REGISTRY }}/mybigpai/pairag:$IMAGE_TAG -f Dockerfile_gpu .
          docker push ${{ env.REGISTRY }}/mybigpai/pairag:$IMAGE_TAG
